---
- name: create docker image
  docker_image:
    name: devops
    build:
      path: /var/lib/jenkins/workspace/MyappPipline
      pull: no 
    source: build
    force_source: true
  vars:
    ansible_python_interpreter: /bin/python3
-  name: run container docker
   docker_container:
     name: myapp_container
     image: devops:latest
     state: started
     recreate: true
     ports:
      - "4200:80"


